server:
  port: 8082

spring:
  application:
    name: MessageService

  datasource:
    hikari:
      #jdbc-url: jdbc:h2:mem:msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # memory Mode
      jdbc-url: jdbc:h2:~/message;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # Embedded Mode
      driverClassName: org.h2.Driver
      username: msa
      password: msa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform:  org.hibernate.dialect.H2Dialect

# Swagger URL Path
springdoc:
  swagger-ui:
    path: /message/swagger.html


kafka:
  consumer:
    bootstrap:
      servers: localhost:9092

  producer:
    bootstrap:
      servers: localhost:9092